### ISSUE TITLE
1.1.0 Release

### ISSUE THREAD

**Issue by garrettjoecox** [HarbourMasters/2ship2harkinian#660]
This is intended to track the remaining tasks for 1.1.0 Anyone with access is free to edit this list.

## Must have
- [ ] Changelog (Draft created)
- [ ] Investigate if our "rom validating" mechanism works. Some people have reported successfully extracted non matching roms which can lead to issues
- [ ] Port over OTR version prompting for reextraction #822
- [x] #525 (probably solved by #743)
- [x] LUS Bump
- [x] Identify issue with items being assigned to B (maybe autosaves?) (probably solved by #740)
- [x] #661 
- [x] #701

## Should have
- [ ] #115 
- [x] #437 
- [x] #475 
- [x] HD Texture Support
  - [x] #794
  - [x] #780
  - [x] #756
  - [x] #783
- [x] #596 
- [x] GFX Debugger is broken (maybe https://github.com/Kenix3/libultraship/commit/caa661b0267c9bb26123cbf6c78d80e97b9012d5 is related?) (Archez: Not an issue directly with debugger, just previous frame data being stuck until a later graphics instruction is selected that renders the clear rectangle)
- [x] #508 
- [x] #533 
- [x] #645 
- [x] #649 
- [x] #537 
- [x] #652
- [x] #756

## Nice to have
- [ ] #408 
- [ ] #595 
- [x] #801 
- [x] #633
- [x] #658
- [x] #535

**Comment by Dooplis** [comment]
Hey, so my navigation bar and menus are way too small for my resolution, I have to get super close to my screen to be able to read for instance the enhancement tab. I remember SoH having the same problem for me, but had the setting to scale it. 
I'm using a 55-inch TV at 4k 250% scale in windows. Can you please add Navigation bar and menu scaling to the list please? 
Thanks for reading and doing your part in making this great thing come to life.

I'll be adding this to issues I was just seeing if this problems been mentioned already.

**Comment by Malkierian** [comment]
@Dooplis I believe this was meant as a "these currently open PRs should be merged for 1.1", not a list of things to do before that release, however, do me a favor and download a build from the Modern Menu PR up there and tell me how it plays on that high of DPI, because I don't have the capacity for testing something like that.

**Comment by Dooplis** [comment]
@Malkierian Ok, so I tried it out, and it's actually bigger so it's easier to read, I just think the total thing might be too small for my screen because it's significantly smaller than the window size, but readable, since my cursor didn't show in screenshot of 
me with the regular menu, so it didn't look nearly as bad to me, I'm hoping you can see what you need, hope this helps.
Maximised window
![maximised](https://github.com/user-attachments/assets/f185cf29-7503-4c3e-8daf-287f288a872f)
not maxed window
![not maximised lol](https://github.com/user-attachments/assets/bf240feb-7f92-4e5e-807a-75b8a058b8e6)


  I'm tempted to use this build if it's with a nightly build that works with HD textures, at least until a scaler comes out

**Comment by Malkierian** [comment]
I mean, you're welcome to, but I'd hold off, since it looks like a release is just around the corner.
